<a href="https://colab.research.google.com/github/adyaomnkar/Deep_learning_with_python/blob/main/Intro_to_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Intro to Tensors

In [5]:
import torch
import numpy as np

In [3]:
#Lists
list=[1,2,3,4,5]
print(list)
my_list=[[1,2,3],[123,124,125]]
my_list


[1, 2, 3, 4, 5]


[[1, 2, 3], [123, 124, 125]]

In [6]:
#Numpy Arrays
np1=np.random.rand(3,4)
np1


array([[0.08923677, 0.78497193, 0.19027072, 0.80855975],
       [0.22488713, 0.76397373, 0.09481097, 0.66150271],
       [0.07202142, 0.76402281, 0.8572633 , 0.24119832]])

In [7]:
# Tensors
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 0.7894, -0.9050,  0.4173, -0.3866],
        [-0.0739, -0.4892, -0.8254,  0.3556],
        [-1.0400, -0.4864, -0.4262, -0.8656]])

In [11]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
## Create a tensor out of numpy arrays
my_tensors=torch.tensor(np1)
my_tensors

tensor([[0.0892, 0.7850, 0.1903, 0.8086],
        [0.2249, 0.7640, 0.0948, 0.6615],
        [0.0720, 0.7640, 0.8573, 0.2412]], dtype=torch.float64)

In [14]:
my_tensors.dtype #because np1 is float64

torch.float64